### PR TITLE
Update dependency class-validator to v0.13.1 & Fixed build

### PR DESCRIPTION
**Pull request by BorntraegerMarc**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[X] No
```

## Other information

I would appreciate some guidance how this new `getTargetValidationMetadatas` should be used. Because I have no knowledge of the functionality. Just wanted to make the new class-validator version know.

Also I'd appreciate some guidance whether new unit tests are needed.

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Thank you @BorntraegerMarc! Merged & published as v0.3.0

**Comment by BorntraegerMarc** [comment]
@kamilmysliwiec thank you for the quick respone.

Just to clarify: Did you see my text in the PR?

> I would appreciate some guidance how this new getTargetValidationMetadatas should be used. Because I have no knowledge of the functionality. Just wanted to make the new class-validator version know.

I'd appreciate a quick confirmation. Not that we release something to the public that's broken...

**Comment by kamilmysliwiec** [comment]
Honestly, I'm not an expert in terms of this library (class-validator) either. I've spent some time investigating the source code and I found this method that lets us retrieve metadata objects by "target" (a class reference in this case) which is exactly what we need here. I've tested your changes (+ pushed a small fix that build for older versions won't fail) and it works as expected :)

**Comment by BorntraegerMarc** [comment]
You not being an expert in something? Hard to imagine 😉

OK, thanks for the confirmation. This will make me sleep calmer at night 🙂

**Pull request merged**
